# This module defines strings containing XPM data that matches
# Golly's built-in icons (see the XPM data in wxalgos.cpp).
# The strings are used by icon-importer.py and icon_exporter.py.

circles = '''
XPM
/* width height num_colors chars_per_pixel */
"31 31 5 1"
/* colors */
". c #000000"
"B c #404040"
"C c #808080"
"D c #C0C0C0"
"E c #FFFFFF"
/* icon for state 1 */
"..............................."
"..............................."
"..........BCDEEEEEDCB.........."
".........CEEEEEEEEEEEC........."
".......BEEEEEEEEEEEEEEEB......."
"......DEEEEEEEEEEEEEEEEED......"
".....DEEEEEEEEEEEEEEEEEEED....."
"....BEEEEEEEEEEEEEEEEEEEEEB...."
"....EEEEEEEEEEEEEEEEEEEEEEE...."
"...CEEEEEEEEEEEEEEEEEEEEEEEC..."
"..BEEEEEEEEEEEEEEEEEEEEEEEEEB.."
"..CEEEEEEEEEEEEEEEEEEEEEEEEEC.."
"..DEEEEEEEEEEEEEEEEEEEEEEEEED.."
"..EEEEEEEEEEEEEEEEEEEEEEEEEEE.."
"..EEEEEEEEEEEEEEEEEEEEEEEEEEE.."
"..EEEEEEEEEEEEEEEEEEEEEEEEEEE.."
"..EEEEEEEEEEEEEEEEEEEEEEEEEEE.."
"..EEEEEEEEEEEEEEEEEEEEEEEEEEE.."
"..DEEEEEEEEEEEEEEEEEEEEEEEEED.."
"..CEEEEEEEEEEEEEEEEEEEEEEEEEC.."
"..BEEEEEEEEEEEEEEEEEEEEEEEEEB.."
"...CEEEEEEEEEEEEEEEEEEEEEEEC..."
"....EEEEEEEEEEEEEEEEEEEEEEE...."
"....BEEEEEEEEEEEEEEEEEEEEEB...."
".....DEEEEEEEEEEEEEEEEEEED....."
"......DEEEEEEEEEEEEEEEEED......"
".......BEEEEEEEEEEEEEEEB......."
".........CEEEEEEEEEEEC........."
"..........BCDEEEEEDCB.........."
"..............................."
"..............................."

XPM
/* width height num_colors chars_per_pixel */
"15 15 5 1"
/* colors */
". c #000000"
"B c #404040"
"C c #808080"
"D c #C0C0C0"
"E c #FFFFFF"
/* icon for state 1 */
"..............."
"....BDEEEDB...."
"...DEEEEEEED..."
"..DEEEEEEEEED.."
".BEEEEEEEEEEEB."
".DEEEEEEEEEEED."
".EEEEEEEEEEEEE."
".EEEEEEEEEEEEE."
".EEEEEEEEEEEEE."
".DEEEEEEEEEEED."
".BEEEEEEEEEEEB."
"..DEEEEEEEEED.."
"...DEEEEEEED..."
"....BDEEEDB...."
"..............."

XPM
/* width height num_colors chars_per_pixel */
"7 7 6 1"
/* colors */
". c #000000"
"B c #404040"
"C c #808080"
"D c #C0C0C0"
"E c #FFFFFF"
"F c #E0E0E0"
/* icon for state 1 */
".BFEFB."
"BEEEEEB"
"FEEEEEF"
"EEEEEEE"
"FEEEEEF"
"BEEEEEB"
".BFEFB."
'''

diamonds = '''
XPM
/* width height num_colors chars_per_pixel */
"31 31 2 1"
/* colors */
". c #000000"
"B c #FFFFFF"
/* icon for state 1 */
"..............................."
"..............................."
"...............B..............."
"..............BBB.............."
".............BBBBB............."
"............BBBBBBB............"
"...........BBBBBBBBB..........."
"..........BBBBBBBBBBB.........."
".........BBBBBBBBBBBBB........."
"........BBBBBBBBBBBBBBB........"
".......BBBBBBBBBBBBBBBBB......."
"......BBBBBBBBBBBBBBBBBBB......"
".....BBBBBBBBBBBBBBBBBBBBB....."
"....BBBBBBBBBBBBBBBBBBBBBBB...."
"...BBBBBBBBBBBBBBBBBBBBBBBBB..."
"..BBBBBBBBBBBBBBBBBBBBBBBBBBB.."
"...BBBBBBBBBBBBBBBBBBBBBBBBB..."
"....BBBBBBBBBBBBBBBBBBBBBBB...."
".....BBBBBBBBBBBBBBBBBBBBB....."
"......BBBBBBBBBBBBBBBBBBB......"
".......BBBBBBBBBBBBBBBBB......."
"........BBBBBBBBBBBBBBB........"
".........BBBBBBBBBBBBB........."
"..........BBBBBBBBBBB.........."
"...........BBBBBBBBB..........."
"............BBBBBBB............"
".............BBBBB............."
"..............BBB.............."
"...............B..............."
"..............................."
"..............................."

XPM
/* width height num_colors chars_per_pixel */
"15 15 2 1"
/* colors */
". c #000000"
"B c #FFFFFF"
/* icon for state 1 */
"..............."
".......B......."
"......BBB......"
".....BBBBB....."
"....BBBBBBB...."
"...BBBBBBBBB..."
"..BBBBBBBBBBB.."
".BBBBBBBBBBBBB."
"..BBBBBBBBBBB.."
"...BBBBBBBBB..."
"....BBBBBBB...."
".....BBBBB....."
"......BBB......"
".......B......."
"..............."

XPM
/* width height num_colors chars_per_pixel */
"7 7 2 1"
/* colors */
". c #000000"
"B c #FFFFFF"
/* icon for state 1 */
"...B..."
"..BBB.."
".BBBBB."
"BBBBBBB"
".BBBBB."
"..BBB.."
"...B..."
'''

hexagons = '''
XPM
/* width height num_colors chars_per_pixel */
"31 31 3 1"
/* colors */
". c #000000"
"B c #FFFFFF"
"C c #808080"
/* icon for state 1 */
".....BBC......................."
"....BBBBBC....................."
"...BBBBBBBBC..................."
"..BBBBBBBBBBBC................."
".BBBBBBBBBBBBBBC..............."
"BBBBBBBBBBBBBBBBBC............."
"BBBBBBBBBBBBBBBBBBBC..........."
"CBBBBBBBBBBBBBBBBBBBBC........."
".BBBBBBBBBBBBBBBBBBBBBB........"
".CBBBBBBBBBBBBBBBBBBBBBC......."
"..BBBBBBBBBBBBBBBBBBBBBB......."
"..CBBBBBBBBBBBBBBBBBBBBBC......"
"...BBBBBBBBBBBBBBBBBBBBBB......"
"...CBBBBBBBBBBBBBBBBBBBBBC....."
"....BBBBBBBBBBBBBBBBBBBBBB....."
"....CBBBBBBBBBBBBBBBBBBBBBC...."
".....BBBBBBBBBBBBBBBBBBBBBB...."
".....CBBBBBBBBBBBBBBBBBBBBBC..."
"......BBBBBBBBBBBBBBBBBBBBBB..."
"......CBBBBBBBBBBBBBBBBBBBBBC.."
".......BBBBBBBBBBBBBBBBBBBBBB.."
".......CBBBBBBBBBBBBBBBBBBBBBC."
"........BBBBBBBBBBBBBBBBBBBBBB."
".........CBBBBBBBBBBBBBBBBBBBBC"
"...........CBBBBBBBBBBBBBBBBBBB"
".............CBBBBBBBBBBBBBBBBB"
"...............CBBBBBBBBBBBBBB."
".................CBBBBBBBBBBB.."
"...................CBBBBBBBB..."
".....................CBBBBB...."
".......................CBB....."

XPM
/* width height num_colors chars_per_pixel */
"15 15 3 1"
/* colors */
". c #000000"
"B c #FFFFFF"
"C c #808080"
/* icon for state 1 */
"...BBC........."
"..BBBBBC......."
".BBBBBBBBC....."
"BBBBBBBBBBB...."
"BBBBBBBBBBBB..."
"CBBBBBBBBBBBC.."
".BBBBBBBBBBBB.."
".CBBBBBBBBBBBC."
"..BBBBBBBBBBBB."
"..CBBBBBBBBBBBC"
"...BBBBBBBBBBBB"
"....BBBBBBBBBBB"
".....CBBBBBBBB."
".......CBBBBB.."
".........CBB..."

XPM
/* width height num_colors chars_per_pixel */
"7 7 3 1"
/* colors */
". c #000000"
"B c #FFFFFF"
"C c #808080"
/* icon for state 1 */
".BBC..."
"BBBBB.."
"BBBBBB."
"CBBBBBC"
".BBBBBB"
"..BBBBB"
"...CBB."
'''

triangles = '''
XPM
/* width height num_colors chars_per_pixel */
"31 93 2 1"
/* colors */
". c #000000"
"B c #FFFFFF"
/* icon for state 1 */
"..............................."
"B.............................."
"BB............................."
"BBB............................"
"BBBB..........................."
"BBBBB.........................."
"BBBBBB........................."
"BBBBBBB........................"
"BBBBBBBB......................."
"BBBBBBBBB......................"
"BBBBBBBBBB....................."
"BBBBBBBBBBB...................."
"BBBBBBBBBBBB..................."
"BBBBBBBBBBBBB.................."
"BBBBBBBBBBBBBB................."
"BBBBBBBBBBBBBBB................"
"BBBBBBBBBBBBBBBB..............."
"BBBBBBBBBBBBBBBBB.............."
"BBBBBBBBBBBBBBBBBB............."
"BBBBBBBBBBBBBBBBBBB............"
"BBBBBBBBBBBBBBBBBBBB..........."
"BBBBBBBBBBBBBBBBBBBBB.........."
"BBBBBBBBBBBBBBBBBBBBBB........."
"BBBBBBBBBBBBBBBBBBBBBBB........"
"BBBBBBBBBBBBBBBBBBBBBBBB......."
"BBBBBBBBBBBBBBBBBBBBBBBBB......"
"BBBBBBBBBBBBBBBBBBBBBBBBBB....."
"BBBBBBBBBBBBBBBBBBBBBBBBBBB...."
"BBBBBBBBBBBBBBBBBBBBBBBBBBBB..."
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBB.."
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB."
/* icon for state 2 */
".BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
"..BBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
"...BBBBBBBBBBBBBBBBBBBBBBBBBBBB"
"....BBBBBBBBBBBBBBBBBBBBBBBBBBB"
".....BBBBBBBBBBBBBBBBBBBBBBBBBB"
"......BBBBBBBBBBBBBBBBBBBBBBBBB"
".......BBBBBBBBBBBBBBBBBBBBBBBB"
"........BBBBBBBBBBBBBBBBBBBBBBB"
".........BBBBBBBBBBBBBBBBBBBBBB"
"..........BBBBBBBBBBBBBBBBBBBBB"
"...........BBBBBBBBBBBBBBBBBBBB"
"............BBBBBBBBBBBBBBBBBBB"
".............BBBBBBBBBBBBBBBBBB"
"..............BBBBBBBBBBBBBBBBB"
"...............BBBBBBBBBBBBBBBB"
"................BBBBBBBBBBBBBBB"
".................BBBBBBBBBBBBBB"
"..................BBBBBBBBBBBBB"
"...................BBBBBBBBBBBB"
"....................BBBBBBBBBBB"
".....................BBBBBBBBBB"
"......................BBBBBBBBB"
".......................BBBBBBBB"
"........................BBBBBBB"
".........................BBBBBB"
"..........................BBBBB"
"...........................BBBB"
"............................BBB"
".............................BB"
"..............................B"
"..............................."
/* icon for state 3 */
".BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
"B.BBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
"BB.BBBBBBBBBBBBBBBBBBBBBBBBBBBB"
"BBB.BBBBBBBBBBBBBBBBBBBBBBBBBBB"
"BBBB.BBBBBBBBBBBBBBBBBBBBBBBBBB"
"BBBBB.BBBBBBBBBBBBBBBBBBBBBBBBB"
"BBBBBB.BBBBBBBBBBBBBBBBBBBBBBBB"
"BBBBBBB.BBBBBBBBBBBBBBBBBBBBBBB"
"BBBBBBBB.BBBBBBBBBBBBBBBBBBBBBB"
"BBBBBBBBB.BBBBBBBBBBBBBBBBBBBBB"
"BBBBBBBBBB.BBBBBBBBBBBBBBBBBBBB"
"BBBBBBBBBBB.BBBBBBBBBBBBBBBBBBB"
"BBBBBBBBBBBB.BBBBBBBBBBBBBBBBBB"
"BBBBBBBBBBBBB.BBBBBBBBBBBBBBBBB"
"BBBBBBBBBBBBBB.BBBBBBBBBBBBBBBB"
"BBBBBBBBBBBBBBB.BBBBBBBBBBBBBBB"
"BBBBBBBBBBBBBBBB.BBBBBBBBBBBBBB"
"BBBBBBBBBBBBBBBBB.BBBBBBBBBBBBB"
"BBBBBBBBBBBBBBBBBB.BBBBBBBBBBBB"
"BBBBBBBBBBBBBBBBBBB.BBBBBBBBBBB"
"BBBBBBBBBBBBBBBBBBBB.BBBBBBBBBB"
"BBBBBBBBBBBBBBBBBBBBB.BBBBBBBBB"
"BBBBBBBBBBBBBBBBBBBBBB.BBBBBBBB"
"BBBBBBBBBBBBBBBBBBBBBBB.BBBBBBB"
"BBBBBBBBBBBBBBBBBBBBBBBB.BBBBBB"
"BBBBBBBBBBBBBBBBBBBBBBBBB.BBBBB"
"BBBBBBBBBBBBBBBBBBBBBBBBBB.BBBB"
"BBBBBBBBBBBBBBBBBBBBBBBBBBB.BBB"
"BBBBBBBBBBBBBBBBBBBBBBBBBBBB.BB"
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBB.B"
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB."

XPM
/* width height num_colors chars_per_pixel */
"15 45 2 1"
/* colors */
". c #000000"
"B c #FFFFFF"
/* icon for state 1 */
"..............."
"B.............."
"BB............."
"BBB............"
"BBBB..........."
"BBBBB.........."
"BBBBBB........."
"BBBBBBB........"
"BBBBBBBB......."
"BBBBBBBBB......"
"BBBBBBBBBB....."
"BBBBBBBBBBB...."
"BBBBBBBBBBBB..."
"BBBBBBBBBBBBB.."
"BBBBBBBBBBBBBB."
/* icon for state 2 */
".BBBBBBBBBBBBBB"
"..BBBBBBBBBBBBB"
"...BBBBBBBBBBBB"
"....BBBBBBBBBBB"
".....BBBBBBBBBB"
"......BBBBBBBBB"
".......BBBBBBBB"
"........BBBBBBB"
".........BBBBBB"
"..........BBBBB"
"...........BBBB"
"............BBB"
".............BB"
"..............B"
"..............."
/* icon for state 3 */
".BBBBBBBBBBBBBB"
"B.BBBBBBBBBBBBB"
"BB.BBBBBBBBBBBB"
"BBB.BBBBBBBBBBB"
"BBBB.BBBBBBBBBB"
"BBBBB.BBBBBBBBB"
"BBBBBB.BBBBBBBB"
"BBBBBBB.BBBBBBB"
"BBBBBBBB.BBBBBB"
"BBBBBBBBB.BBBBB"
"BBBBBBBBBB.BBBB"
"BBBBBBBBBBB.BBB"
"BBBBBBBBBBBB.BB"
"BBBBBBBBBBBBB.B"
"BBBBBBBBBBBBBB."

XPM
/* width height num_colors chars_per_pixel */
"7 21 2 1"
/* colors */
". c #000000"
"B c #FFFFFF"
/* icon for state 1 */
"......."
"B......"
"BB....."
"BBB...."
"BBBB..."
"BBBBB.."
"BBBBBB."
/* icon for state 2 */
".BBBBBB"
"..BBBBB"
"...BBBB"
"....BBB"
".....BB"
"......B"
"......."
/* icon for state 3 */
".BBBBBB"
"B.BBBBB"
"BB.BBBB"
"BBB.BBB"
"BBBB.BB"
"BBBBB.B"
"BBBBBB."
'''
